---
- hosts: all
  become: true
  tasks:
  - name: Update Ubuntu/Debian
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Update Centos/RHEL
    yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
