---
- hosts: all
  become: true
  tasks:
  - name: Install pkgs
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - make
      - vim
      - wget
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python-pip
  - name: install docker-py via pip
    pip:
      name: docker-py

  - name: add Docker key
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add Docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: install docker
    apt:
      name: docker-ce
      update_cache: yes

  - name: Setup docker container - ssebs-www
    docker_container:
      name: ssebs-website
      image: ssebs/ssebs-www
      user: root
      published_ports:
        - "80:80"
    
#  - name: Setup docker container - nginx-LE reverse proxy
#    docker_container:
#      name: ssebs-ssl
#      image: bradjonesllc/docker-nginx-letsencrypt
#      user: root
#      published_ports:
#        - "80:80"
#        - "443:443"
#      env:
#         CERTS: "ssebs.com,home.ssebs.com,cms.ssebs.com"
#         EMAIL: "ssebs@ssebs.com"
#      volumes:
#        - "/etc/ssl/dhparam:/etc/ssl/dhparam"
#        - "/srv/letsencrypt:/etc/letsencrypt"


